# Generated by Django 5.1.5 on 2026-01-17 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('season', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Crop Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgriOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agri_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['district'],
            },
        ),
        migrations.CreateModel(
            name='AgriUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('update_type', models.CharField(choices=[('weather', 'Weather Alert'), ('market', 'Market Price'), ('scheme', 'Government Scheme'), ('advisory', 'General Advisory'), ('pest', 'Pest Alert')], max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agri_updates/')),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates_posted', to='agriculture.agriofficer')),
                ('crop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='agriculture.cropcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='farmer_queries/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('answered', 'Answered'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('query_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queries', to='agriculture.agriofficer')),
                ('crop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='agriculture.cropcategory')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Farmer Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgriAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
                ('is_validated', models.BooleanField(default=False)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='agri_advisories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories_given', to='agriculture.agriofficer')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_advisories', to='agriculture.agriofficer')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='agriculture.farmerquery')),
            ],
            options={
                'verbose_name_plural': 'Agricultural Advisories',
                'ordering': ['-created_at'],
            },
        ),
    ]
