# Generated by Django 5.1.5 on 2026-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorunavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorunavailability',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorunavailability',
            name='recurrence_pattern',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorunavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
